# Generated by Django 3.2 on 2023-02-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0002_auto_20230219_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultroom',
            name='room_text',
            field=models.TextField(blank=True, null=True, verbose_name='Room Text'),
        ),
        migrations.AddField(
            model_name='operatingroom',
            name='room_text',
            field=models.TextField(blank=True, null=True, verbose_name='Room Text'),
        ),
    ]
