# Generated by Django 3.2 on 2023-02-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0003_auto_20230219_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultroom',
            name='room_text',
            field=models.TextField(default='', verbose_name='Room Text'),
        ),
        migrations.AlterField(
            model_name='operatingroom',
            name='room_text',
            field=models.TextField(default='', verbose_name='Room Text'),
        ),
    ]
