# Generated by Django 3.2 on 2023-02-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0005_datatracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingroom',
            name='text_input_1',
            field=models.CharField(default='', max_length=50, verbose_name='Room Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatingroom',
            name='text_input_2',
            field=models.CharField(default='', max_length=50, verbose_name='Room Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operatingroom',
            name='text_input_3',
            field=models.CharField(default='', max_length=50, verbose_name='Room Name'),
            preserve_default=False,
        ),
    ]
