# Generated by Django 3.2 on 2023-02-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0006_auto_20230222_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operatingroom',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='operatingroom',
            name='room_status',
        ),
        migrations.RemoveField(
            model_name='operatingroom',
            name='room_text',
        ),
        migrations.AlterField(
            model_name='operatingroom',
            name='text_input_1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='operatingroom',
            name='text_input_2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='operatingroom',
            name='text_input_3',
            field=models.TextField(),
        ),
    ]
